# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Hoofy < Formula
  desc "Spec-Driven Development MCP Server — persistent memory, adaptive changes, clarity gate"
  homepage "https://github.com/HendryAvila/Hoofy"
  version "0.12.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/HendryAvila/Hoofy/releases/download/v0.12.0/hoofy_0.12.0_darwin_amd64.tar.gz"
      sha256 "18232934a263395e007ab029da4fea2c9ec9cfd4e4fb83044180800e06e09ba3"

      define_method(:install) do
        bin.install "hoofy"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/HendryAvila/Hoofy/releases/download/v0.12.0/hoofy_0.12.0_darwin_arm64.tar.gz"
      sha256 "70f6ab99fa26e00d6d6e152b457153f88a8bb4546adf284677a8b15b1d9accf4"

      define_method(:install) do
        bin.install "hoofy"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/HendryAvila/Hoofy/releases/download/v0.12.0/hoofy_0.12.0_linux_amd64.tar.gz"
      sha256 "28d26af498f5bd64fa6a5ade82d2b5aaf6cd8d9f38f2cafd8d66e1cfd9c0f9dc"
      define_method(:install) do
        bin.install "hoofy"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/HendryAvila/Hoofy/releases/download/v0.12.0/hoofy_0.12.0_linux_arm64.tar.gz"
      sha256 "ff7500747cca9faaa63bb393ea619a94673738940aafe6dd4adf71b1a5172fe2"
      define_method(:install) do
        bin.install "hoofy"
      end
    end
  end

  test do
    system "#{bin}/hoofy", "--version"
  end
end
