# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Hoofy < Formula
  desc "Spec-Driven Development MCP Server — persistent memory, adaptive changes, clarity gate"
  homepage "https://github.com/HendryAvila/Hoofy"
  version "0.12.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/HendryAvila/Hoofy/releases/download/v0.12.0/hoofy_0.12.0_darwin_amd64.tar.gz"
      sha256 "5fa81b877619ac5113ea47c2205f8ef3ed2c9f4eff5f0129f3fa571a2ca5616c"

      define_method(:install) do
        bin.install "hoofy"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/HendryAvila/Hoofy/releases/download/v0.12.0/hoofy_0.12.0_darwin_arm64.tar.gz"
      sha256 "679eb6e0616732dfab87b19f1d7d1bbd966e3e5fcf372148d506641596f529bf"

      define_method(:install) do
        bin.install "hoofy"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/HendryAvila/Hoofy/releases/download/v0.12.0/hoofy_0.12.0_linux_amd64.tar.gz"
      sha256 "36f5e28d26a1db175e12e92fe180dbcf5b35c1471d9449dfa5f95d2528a9027c"
      define_method(:install) do
        bin.install "hoofy"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/HendryAvila/Hoofy/releases/download/v0.12.0/hoofy_0.12.0_linux_arm64.tar.gz"
      sha256 "886046f474c20c64b920e112c7119470d413f2a5801671394457c91e835f85e7"
      define_method(:install) do
        bin.install "hoofy"
      end
    end
  end

  test do
    system "#{bin}/hoofy", "--version"
  end
end
